<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change location' => 'Cambiar locación',
    'Read more about the indicators or ' => 'Más información sobre los indicadores o ',
    'Read more about the sensor types, or ' => 'Más información sobre los tipos de sensores, o ',
    'This is the information for' => 'Esta es la información para',
    'Use Ecosystem Services indicators to gauge characteristics of a catchment.' => 'Utilizar indicadores Servicios de los ecosistemas para medir características de una cuenca.',
    'Use these graphs and maps to explore data collected by local environmental sensors.' => 'Use estos gráficos y mapas para explorar los datos recogidos por los sensores ambientales locales.',
    'located in' => 'situado en',
    'select a sensor' => 'seleccionar un sensor',
    'to start.' => 'para comenzar.',
];
