<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "file".
 *
 * @property integer $id
 * @property string $filelink
 * @property string $filename
 * @property string $extension
 * @property string $startdate
 * @property string $enddate
 * @property string $status
 * @property integer $sensorid
 *
 * @property \app\models\Sensor $sensor
 * @property string $aliasModel
 */
abstract class File extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'file';
    }

    /**
     * Alias name of table for crud viewsLists all Area models.
     * Change the alias name manual if needed later
     * @return string
     */
    public function getAliasModel($plural=false)
    {
        if($plural){
            return Yii::t('file', 'Files');
        }else{
            return Yii::t('file', 'File');
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['startdate', 'enddate'], 'safe'],
            [['sensorid'], 'required'],
            [['sensorid'], 'integer'],
            [['filelink', 'filename', 'extension', 'status'], 'string', 'max' => 255],
            [['sensorid'], 'exist', 'skipOnError' => true, 'targetClass' => Sensor::className(), 'targetAttribute' => ['sensorid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('file', 'ID'),
            'filelink' => Yii::t('file', 'Filelink'),
            'filename' => Yii::t('file', 'Filename'),
            'extension' => Yii::t('file', 'Extension'),
            'startdate' => Yii::t('file', 'Startdate'),
            'enddate' => Yii::t('file', 'Enddate'),
            'status' => Yii::t('file', 'Status'),
            'sensorid' => Yii::t('file', 'Sensorid'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(
            parent::attributeHints(),
            [
            'id' => Yii::t('file', 'ID'),
            'filelink' => Yii::t('file', 'Filelink'),
            'filename' => Yii::t('file', 'Filename'),
            'extension' => Yii::t('file', 'Extension'),
            'startdate' => Yii::t('file', 'Startdate'),
            'enddate' => Yii::t('file', 'Enddate'),
            'status' => Yii::t('file', 'Status'),
            'sensorid' => Yii::t('file', 'Sensorid'),
            ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSensor()
    {
        return $this->hasOne(\app\models\Sensor::className(), ['id' => 'sensorid']);
    }




}
