<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A brief description of what they are summing up the key points and why they are relevant and helpful to policy makers.' => '',
    'About the sensors' => 'यो सेन्सर बारे',
    'Base flow index' => '',
    'Choose a location, date range and/or conservation and the ESS indicator scores will appear here' => '',
    'Compare indicators' => '',
    'Data is being collected in four case study locations: Peru, Kryzgstan, Nepal and Ethiopia.' => 'पेरु, किर्गिस्तान, नेपाल र इथोपिया: डाटा चार मामला अध्ययन स्थानहरूमा संकलित भइरहेको छ।',
    'ESS Indicators explained' => 'ESS सूचक बताए',
    'ESS indicators' => 'ESS सूचक',
    'ESS indicators explained' => 'ESS सूचक बताए',
    'Ecosystem Services in more depth' => '',
    'Eplain' => '',
    'Explain' => '',
    'Explain what sensors are used, how data is collected, etc' => 'के सेन्सर प्रयोग गरिन्छ, व्याख्या, डाटा संकलन कसरी, आदि',
    'Explore two sections on Mountain-Evo:' => 'पहाड-अतुल्य दुई खण्डहरू अन्वेषण:',
    'Find out about Ecosystem Services, and check compare ESS indicator scores' => '',
    'Find out about all the types of weather sensor used in these areas.' => '',
    'Find out what base flow index shows' => 'के आधार प्रवाह सूचकांक शो पत्ता',
    'How is this data collected?' => '',
    'Interpreting the scores' => '',
    'Learn how they measure data' => 'तिनीहरूले डाटा मापन कसरी सिक्न',
    'Mountain-Evo is a shared virtual observatory of remote mountain socio-ecological systems for poverty alleviation.' => 'पहाड-अतुल्य गरिबी alleviation लागि एक साझा भर्चुअल रिमोट पहाड सामाजिक-पारिस्थितिक प्रणाली को वेधशाला छ।',
    'Observatory' => 'वेधशाला',
    'Observatory charts' => 'अवलोकन चार्ट',
    'Pluvio Meter' => '',
    'Put the updated blurb and explanation about the site in here so that people get the website.' => 'यहाँ साइट बारेमा अद्यावधिक भएको ठूलो अक्षरको क्याप्सन र व्याख्या राख्नु मान्छे वेबसाइट प्राप्त भनेर।',
    'Read More' => 'थप पढ्नुहोस्',
    'Read more link' => 'थप पढ्नुहोस्',
    'Runoff ratio' => '',
    'See temperature rainfall, and riverflow data collected, and learn about the sensors' => 'तापमान वर्षा हेर्नुहोस्, र नदी प्रवाह डाटा संकलन र सेन्सर सिक्न',
    'Select to compare to another location, date range and/or conservation type, and view ESS indicator scores here.' => '',
    'Slope of flow duration curve make this scores meaningful.' => 'प्रवाह अवधि वक्र को ढलान यो स्कोर अर्थपूर्ण बनाउन।',
    'Start' => 'सुरु',
    'View ESS indicators' => 'ESS संकेतक हेर्नुहोस्',
    'View rainfall data for a location' => 'एक स्थान लागि वर्षा डाटा हेर्नुहोस्',
    'What are Ecosystem Services?' => 'पारिस्थितिकी तंत्र सेवा के-के हुन्?',
    'What is Mountain-Evo?' => 'पहाड-अतुल्य के हो?',
    'read more' => 'थप पढ्नुहोस्',
];
