<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Change location' => 'स्थान परिवर्तन',
    'Read more about the indicators or ' => 'पढ्ने संकेतक बारेमा थप वा',
    'Read more about the sensor types, or ' => 'सेन्सर प्रकारका बारेमा थप पढ्न, वा',
    'This is the information for' => 'यो लागि जानकारी छ',
    'Use Ecosystem Services indicators to gauge characteristics of a catchment.' => 'एक catchment को विशेषताहरु गेज पारिस्थितिकी तंत्र सेवा संकेतक प्रयोग गर्नुहोस्।',
    'Use these graphs and maps to explore data collected by local environmental sensors.' => 'स्थानीय पर्यावरण सेन्सर संकलित डाटा अन्वेषण गर्न यी रेखांकन र नक्सा प्रयोग गर्नुहोस्।',
    'located in' => 'मा स्थित',
    'select a sensor' => 'एक सेन्सर चयन',
    'to start.' => 'सुरु गर्न।',
];
