<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Catchments' => '',
    'Add Sensor' => 'सेन्सर थप्न',
    'Admin' => 'व्यवस्थापक',
    'ESS indicators' => 'ESS संकेतक',
    'Language' => 'भाषा',
    'Login' => 'लग - इन',
    'Logout' => 'बाहिर निस्कनु',
    'Maps' => 'नक्सा',
    'Observatory' => 'वेधशाला',
    'Rainfall' => 'वर्षा',
    'Riverflow' => 'नदी प्रवाह',
    'Sensor info' => 'सेन्सर जानकारी',
    'Sensors' => 'सेन्सर',
    'Temperature' => 'तापमान',
    'Tracing' => 'सिर्जनागर्दै',
    'Upload Data' => 'अपलोड डाटा',
    'Users' => 'प्रयोगकर्ता',
];
