<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A brief description of what they are summing up the key points and why they are relevant and helpful to policy makers.' => '',
    'About the sensors' => 'Acerca de los sensores',
    'Base flow index' => '',
    'Choose a location, date range and/or conservation and the ESS indicator scores will appear here' => '',
    'Compare indicators' => '',
    'Data is being collected in four case study locations: Peru, Kryzgstan, Nepal and Ethiopia.' => 'Los datos están siendo recogidos en cuatro lugares de estudio de caso : Perú , Kryzgstan , Nepal y Etiopía.',
    'ESS Indicators explained' => 'ESS indicadores explicados',
    'ESS indicators' => 'indicadores del ESS',
    'ESS indicators explained' => 'ESS indicadores explicados',
    'Ecosystem Services in more depth' => 'Los servicios de los ecosistemas en mayor profundidad',
    'Eplain' => 'Explique',
    'Explain' => 'Explique',
    'Explain what sensors are used, how data is collected, etc' => '',
    'Explore two sections on Mountain-Evo:' => 'Explora dos secciones en la montaña - Evo:',
    'Find out about Ecosystem Services, and check compare ESS indicator scores' => 'Averiguar sobre servicios de los ecosistemas , y se les compara puntuaciones de los indicadores del ESS',
    'Find out about all the types of weather sensor used in these areas.' => '',
    'Find out what base flow index shows' => 'Averiguar qué caudal de base espectáculos índice',
    'How is this data collected?' => '',
    'Interpreting the scores' => '',
    'Learn how they measure data' => 'Aprender cómo miden los datos',
    'Mountain-Evo is a shared virtual observatory of remote mountain socio-ecological systems for poverty alleviation.' => 'Montaña - Evo es un observatorio virtual compartida de los sistemas socio- ecológicos de montaña remota para el alivio de la pobreza.',
    'Observatory' => 'Observatorio',
    'Observatory charts' => 'Observatorio de gráficos',
    'Pluvio Meter' => '',
    'Put the updated blurb and explanation about the site in here so that people get the website.' => 'Ponga la propaganda actualizada y una explicación sobre el sitio de aquí, así que la gente consigue la página web.',
    'Read More' => 'Lee mas',
    'Read more link' => 'Lee mas',
    'Runoff ratio' => '',
    'See temperature rainfall, and riverflow data collected, and learn about the sensors' => 'Ver precipitaciones temperatura, y se recogieron los datos de caudal del río, y aprender acerca de los sensores',
    'Select to compare to another location, date range and/or conservation type, and view ESS indicator scores here.' => '',
    'Slope of flow duration curve make this scores meaningful.' => '',
    'Start' => '',
    'View ESS indicators' => '',
    'View rainfall data for a location' => 'Ver datos de precipitación para una ubicación',
    'What are Ecosystem Services?' => '¿Qué son los servicios de los ecosistemas ?',
    'What is Mountain-Evo?' => '¿Cuál es la montaña - Evo ?',
    'read more' => 'Lee mas',
];
