<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A brief description of what they are summing up the key points and why they are relevant and helpful to policy makers.' => '',
    'About the sensors' => '',
    'Base flow index' => '',
    'Choose a location, date range and/or conservation and the ESS indicator scores will appear here' => '',
    'Compare indicators' => '',
    'Data is being collected in four case study locations: Peru, Kryzgstan, Nepal and Ethiopia.' => '',
    'ESS Indicators explained' => '',
    'ESS indicators' => '',
    'ESS indicators explained' => '',
    'Ecosystem Services in more depth' => '',
    'Eplain' => '',
    'Explain' => '',
    'Explain what sensors are used, how data is collected, etc' => '',
    'Explore two sections on Mountain-Evo:' => '',
    'Find out about Ecosystem Services, and check compare ESS indicator scores' => '',
    'Find out about all the types of weather sensor used in these areas.' => '',
    'Find out what base flow index shows' => '',
    'How is this data collected?' => '',
    'Interpreting the scores' => '',
    'Learn how they measure data' => '',
    'Mountain-Evo is a shared virtual observatory of remote mountain socio-ecological systems for poverty alleviation.' => '',
    'Observatory' => '',
    'Observatory charts' => '',
    'Pluvio Meter' => '',
    'Put the updated blurb and explanation about the site in here so that people get the website.' => '',
    'Read More' => '',
    'Read more link' => '',
    'Runoff ratio' => '',
    'See temperature rainfall, and riverflow data collected, and learn about the sensors' => '',
    'Select to compare to another location, date range and/or conservation type, and view ESS indicator scores here.' => '',
    'Slope of flow duration curve make this scores meaningful.' => '',
    'Start' => '',
    'View ESS indicators' => '',
    'View rainfall data for a location' => '',
    'What are Ecosystem Services?' => '',
    'What is Mountain-Evo?' => '',
    'read more' => '',
];
